config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'search#index'
  devise_for :users
  get 'home/index'

  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:show, :new, :create, :destroy]
  
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
  has_many :post_hash_tags
  has_many :posts, through: :post_hash_tags
end

app/models/post.rb
class Post < ApplicationRecord
  after_commit :create_hash_tags, on: :create

  belongs_to :user
  has_one_attached :image
  validate :image_validate

  has_many :post_hash_tags
  has_many :hash_tags, through: :post_hash_tags

  def image_validate
    errors.add(:image, "can't be blank") unless image.attached?
    if image.attached?
      if image.blob.byte_size > 5000000
        image.purge
        errors.add(:image, "should be less than 5MB")
      elsif !image.blob.content_type.starts_with?('image/')
        image.purge
        errors.add(:image, "Wrong format")
      end
    end
  end

  def create_hash_tags
    extract_name_hash_tags.each do |name|
      hash_tags.create(name: name)
    end
  end

  def extract_name_hash_tags
    description.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
  end
  
end

app/models/post_hash_tag.rb
class PostHashTag < ApplicationRecord
  belongs_to :post
  belongs_to :hash_tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy

  has_one_attached :avatar
  validate :avatar_validate

   def avatar_validate
    if avatar.attached?
      if avatar.blob.byte_size > 2000000
        avatar.purge
        errors.add(:avatar, "should be less than 2MB")
      elsif !avatar.blob.content_type.starts_with?('image/')
        avatar.purge
        errors.add(:avatar, "Wrong format")
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    
    redirect_to user_path(current_user)
  end

  private
  
  def post_params
    params.require(:post).permit(:description, :image, :user_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController  
  def index
    if params[:query].start_with?('#')
      query  = params[:query].gsub('#', '')
      @posts = Post.joins(:hash_tags).where(hash_tags: {name: query})
    else
      @posts = Post.where("description like ?", "%#{params[:query]}%")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user  = User.find(params[:id])
    @posts = current_user.posts.order(created_at: :desc)
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :website, :bio, :email, :phone, :gender, :avatar)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Gossip</h1>
<p>Last gossips around the globe</p>
<% if current_user %>
  <div class='form-upload'>
    <%= form_for Post.new do |f| %>
      <div class="form-group">
        <%= f.text_field :description %>
      </div>
      <div class="form-group">
        <%= f.file_field :image, onchange: "validateFiles(this);",
          data: { max_file_size: 5.megabytes }
        %>
      </div>
      <div class="form-group">
          <%= f.text_field :user_id, value: current_user.id, class:'d-none'%>
      </div>
      <br>
      <div class="text-center">
        <%= f.submit 'Create Post', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
<% else %>
  <a href="<%= new_user_session_path%>">
    Log in to see more gossips!
  </a>
<% end %>

<div class="posts">
  <% @posts.each do |post| %>
    <section class="post">
      <div class="user">
        <div class="avatar">
          <%= link_to user_path(post.user) do %>
            <% if post.user.avatar.attached? %>  
              <%= image_tag post.user.avatar %>
            <% else %>
              <img src="https://ui-avatars.com/api/?background=0D8ABC&color=fff&name=CS">
            <% end %>
          <% end %>
        </div>
        <div class="username">
          <%= link_to post.user.username, user_path(post.user), class: 'username' %>
        </div>
      </div>
      <div class="centeredFlex">
        <%=link_to post_path(post) do %>
          <%= image_tag post.image, class: 'main-image' %>
        <% end %>
      </div>
      <div class="description">
        <% post.description.to_s.split(' ').each do |word| %>
          <% if word.start_with?('#') %>
            <%= link_to word, search_path(query: word) %>
          <%else %>
            <%= word %>
          <%end %>
        <% end %>
      </div>
    </section>
  <% end %>
  <%= paginate @posts %>
</div>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Gossip</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="/">
            <%= fa_stacked_icon "camera inverse", base: "circle"%>
            Gossip
          </a>
        </div>
        <div class="m-auto">
          <%= form_with url: search_path, method: :get, local: true, class: 'form-inline search-form' do |form| %>
            <%= form.text_field :query, value: params[:query], class: 'form-control mr-sm-2', placeholder: '#search' %>
          <% end %>
        </div>
        <div class="user-section">
          <a><i class="fa fa-compass"></i></a>
          <a><i class="fa fa-heart"></i></a>
          <% if user_signed_in? %>
            <a href="<%= user_path(current_user)%>" data-method="delete">
              <i class="fa fa-user"></i>
            </a>
          <% else %>
            <a href="<%= new_user_session_path%>">
              <i class="fa fa-sign-in"></i>
            </a>
          <% end %>
        </div>
      </div>
    </nav>

    <!--Main content-->
    <main class="container" style="min-height: 500px;">
      <%= yield %>
    </main>

    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>About us
          </li>
          <li>Support</li>
          <li>Press</li>
          <li>API</li>
          <li>Jobs</li>
          <li>Privacy</li>
          <li>Terms</li>
          <li>Directory</li>
          <li>Profiles</li>
          <li>Hasgtags</li>
          <li>Language</li>
        </ul>
        <p> © 2019 Gossip </p>
      </nav>
    </footer>
  </body>
</html>
  </body>
</html>

app/views/posts/show.html.erb
<div class="post-show row">
  <div class="col-md-8">
    <%=image_tag @post.image, class: 'image' %>
  </div>
  <div class="col-md-4">
    <div class="user">
      <div class="avatar">
        <% if @post.user.avatar.attached? %>
          <%= link_to user_path(@post.user) do %>
            <%= image_tag @post.user.avatar %>
          <% end %>
        <% end %>
      </div>
      <%= link_to @post.user.username, user_path(@post.user), class: 'username' %>
    </div>
    <div class="description">
      <%= @post.description %>
    </div>
    <div class="delete">
      <% if current_user.posts.exists?(@post.id) %>
        <%= link_to 'Remove', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
  
</div>

app/views/search/index.html.erb
<div class="search-page">
  <% if @posts.exists? %>
    <h1>Top Posts</h1>
  <% else %>
    <h1>Oop! No matching posts ...</h1>
  <% end %>
<div class="user-images">
    <% @posts.each do |post|%>
      <div class="wrapper">
        <%=image_tag post.image %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
      <a class="nav-link" data-toggle="pill">Change Password</a>
      <a class="nav-link" data-toggle="pill">Authorized Applications</a>
      <a class="nav-link" data-toggle="pill">Email and SMS</a>
      <a class="nav-link" data-toggle="pill">Manage Contacts</a>
      <a class="nav-link" data-toggle="pill">Privacy and Security</a>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
        <div class="form-group row">
          <div class="col-sm-3 col-form-label">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: 'avatar' %>
            <% else %>
              <img src="https://ui-avatars.com/api/?background=0D8ABC&color=fff&name=CS">
            <%end %>
          </div>
          <div class="col-sm-9">
            <p class="username"><%=current_user.username %></p>
            <a class="change-photo" href="#avatar">Change Profile Photo</a>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :name, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :username, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :website, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :website, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_area :bio, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row" id="avatar">
          <%= f.label :avatar, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.file_field :avatar, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :email, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :phone, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :phone, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :gender, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :gender, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-3">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Submit", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar %>
        <% else %>
            <img src="https://ui-avatars.com/api/?background=0D8ABC&color=fff&name=CS">
        <%end %>
      </div>
    </div>
    
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%=current_user.username %></h2>
        <a class="edit-profile" href="<%= edit_user_path(current_user) %>">
          <button>Edit Profile</button>
        </a>
      </div>
      <h2 class="name"><%= current_user.name %></h2>
      <%=link_to current_user.website, current_user.website, class:  'website' %>
      <ul class="profileStatistics">
        <li><span><%= @posts.count %></span> posts</li>
        <li><span>195</span> followers</li>
        <li><span>345</span> following</li>
      </ul>
    </div>
  </div>
</div>

<div class="user-tabs">
  <a class="tab active" href="">
    <i class="fa fa-th"></i>
    Posts
  </a>
  <a class="tab" href="">
    <i class="fa fa-tv"></i>
    Videos
  </a>
  <a class="tab" href="">
    <i class="fa fa-bookmark"></i>
    Saved
  </a>
  <a class="tab" href="">
    <i class="fa fa-tag"></i>
    Tagged
  </a>
</div>

<div class="user-images">
  <% @posts.each do |post|%>
    <div class="wrapper">
    <%=link_to post_path(post) do %>
      <%=image_tag post.image %>
    <% end %>
    </div>
  <% end %>
</div>